<?php
/*
 * MySql Database Connector
 */

class db
{
	private static $con;
	private static $db;
	private static $host;
	private static $port;
	private static $user;
	private static $pass;

	
	/*
	 * Initializes the database connection with the default configuration.
	 */
	
	public function __construct(){
        
        self::$db = 'info_database';
        //self::$host = 'xxxxxx';
        self::$host = 'localhost';
        self::$port = 3306;
        self::$user = 'user';
        self::$pass = 'Coelho16#';
        
				
		self::$con = mysqli_connect(self::$host, self::$user, self::$pass, self::$db);
	
		if (!self::$con){
  			exit('Could not connect: ' . mysqli_connect_error());
  		} else {
  			//mysqli_set_time(self::$con, "'" . Datetime_Handler::get_gmt_time() . "';");
  		}
  		
  		mysqli_set_charset(self::$con, "utf8");
  		
	}
	
	/*
	 * Get the database connection.
	 */
	public function get_connection() {
		return self::$con;
	}
	
	/*
	 * Closes the database connection.
	 */
	public function close(){
		self::$rollback();
		mysqli_close(self::$con);
	}
	
	/*
	 * Executes a query on the connected database.
	 * 
	 * Parameters:
	 * 		$sql - The query to be executed.
	 * 
	 * Returns the query handler. 
	 */
	public function query($sql){
		return mysqli_query(self::$con, $sql);
	}
	
	/*
	 * Fetches the next row from the executed query.
	 * 
	 * Parameters:
	 * 		$result - The query handler.
	 * 		$assoc - Result as associative array
	 * 
	 * Returns an array representing the next row.
	 */
	public function get_next_row($result, $assoc = false){
		if (!$result)
			return null;
		
		if ($assoc)
			return mysqli_fetch_assoc($result);
		else
			return mysqli_fetch_array($result);
	}
	
	/*
	 * Returns the sql query result number of rows.
	 */
	public function get_rows($result){
		
		//if(is_bool($result))
			//die(print("ERROR GET ROWS"));
			
		return mysqli_num_rows($result);
		
	}
	
	/*
	 * Executes an update query on the connected database.
	 * 
	 * Parameters:
	 * 		$sql - The query to be executed.
	 * 
	 * Returns the number of affected rows. 
	 */
	public function update($sql){
		mysqli_query(self::$con, $sql);
		return mysqli_affected_rows(self::$con);
	}
	
	/*
	 * Fetches the id generated by the last update query.
	 * 
	 * Returns the fetched id.
	 */
	public function get_last_inserted_id() {
		return mysqli_insert_id(self::$con);
	}
	
	/*
	 * Escapes special characters in the unescaped_string.
	 * 
	 * Returns the escaped string.
	 */
	public function sql_escape_string($unescaped_string) {
		//$unescaped_string = addslashes($unescaped_string);
		return mysqli_real_escape_string(self::$con, $unescaped_string);
	}
	
	/*
	 * Starts a transaction and stops auto commiting.
	 */
	public function start_transaction () {
		self::query("begin");
	}
	
	/*
	 * Commits a transaction and saves all changes to the database since a "start_transaction" command.
	 */
	public function commit () {
		self::query("commit");
	}
	
	/*
	 * Rollbacks a transaction and discards all changes since a "start_transaction" command.
	 */
	public function rollback () {
		self::query("rollback");
	}
}

?>
